version: '3.8'

services:
  web:
    container_name: hotelinking_api_server
    build:
      context: ./
      dockerfile: web.docker
    volumes:
      - ./:/var/www
    ports:
      - "127.0.0.1:${DOCKER_APP_PORT:-8120}:80"
    depends_on:
      - app
    networks:
      - hotelinking

  app:
    container_name: hotelinking_api_app
    build:
      context: ./
      dockerfile: api.docker
    volumes:
      - ./:/var/www
    environment:
      - DB_HOST=hlmysql8
      - DB_PORT=3306
      - DB_DATABASE=hotelinking_app_local
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    networks:
      - hotelinking

  db:
    image: mysql:8.0
    container_name: hlmysql8
    command: --log-bin-trust-function-creators=1 --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: hotelinking_app_local
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      hotelinking:
        aliases:
          - hlmysql8
          - hldb

  redis:
    image: redis:6-alpine
    container_name: hlredis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      hotelinking:
        aliases:
          - redis

networks:
  hotelinking:
    external: true

volumes:
  mysql_data:
  redis_data:
